/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const FormsIndexLazyImport = createFileRoute('/forms/')()
const AuthIndexLazyImport = createFileRoute('/auth/')()
const FormsQuizIdLazyImport = createFileRoute('/forms/$quizId')()
const AuthFinishSignUpIndexLazyImport = createFileRoute('/auth/finishSignUp/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FormsIndexLazyRoute = FormsIndexLazyImport.update({
  path: '/forms/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/forms/index.lazy').then((d) => d.Route))

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))

const FormsQuizIdLazyRoute = FormsQuizIdLazyImport.update({
  path: '/forms/$quizId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/forms/$quizId.lazy').then((d) => d.Route))

const AuthFinishSignUpIndexLazyRoute = AuthFinishSignUpIndexLazyImport.update({
  path: '/auth/finishSignUp/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/finishSignUp/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/forms/$quizId': {
      id: '/forms/$quizId'
      path: '/forms/$quizId'
      fullPath: '/forms/$quizId'
      preLoaderRoute: typeof FormsQuizIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/finishSignUp/': {
      id: '/auth/finishSignUp/'
      path: '/auth/finishSignUp'
      fullPath: '/auth/finishSignUp'
      preLoaderRoute: typeof AuthFinishSignUpIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/forms/$quizId': typeof FormsQuizIdLazyRoute
  '/auth': typeof AuthIndexLazyRoute
  '/forms': typeof FormsIndexLazyRoute
  '/auth/finishSignUp': typeof AuthFinishSignUpIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/forms/$quizId': typeof FormsQuizIdLazyRoute
  '/auth': typeof AuthIndexLazyRoute
  '/forms': typeof FormsIndexLazyRoute
  '/auth/finishSignUp': typeof AuthFinishSignUpIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/forms/$quizId': typeof FormsQuizIdLazyRoute
  '/auth/': typeof AuthIndexLazyRoute
  '/forms/': typeof FormsIndexLazyRoute
  '/auth/finishSignUp/': typeof AuthFinishSignUpIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forms/$quizId' | '/auth' | '/forms' | '/auth/finishSignUp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forms/$quizId' | '/auth' | '/forms' | '/auth/finishSignUp'
  id:
    | '__root__'
    | '/'
    | '/forms/$quizId'
    | '/auth/'
    | '/forms/'
    | '/auth/finishSignUp/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FormsQuizIdLazyRoute: typeof FormsQuizIdLazyRoute
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
  FormsIndexLazyRoute: typeof FormsIndexLazyRoute
  AuthFinishSignUpIndexLazyRoute: typeof AuthFinishSignUpIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FormsQuizIdLazyRoute: FormsQuizIdLazyRoute,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
  FormsIndexLazyRoute: FormsIndexLazyRoute,
  AuthFinishSignUpIndexLazyRoute: AuthFinishSignUpIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/forms/$quizId",
        "/auth/",
        "/forms/",
        "/auth/finishSignUp/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/forms/$quizId": {
      "filePath": "forms/$quizId.lazy.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.lazy.tsx"
    },
    "/forms/": {
      "filePath": "forms/index.lazy.tsx"
    },
    "/auth/finishSignUp/": {
      "filePath": "auth/finishSignUp/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
